### ISSUE TITLE
Question about the training process

### ISSUE THREAD

**Issue by harukaza** [cs-mshah/CDUL#1]
What different about the _make evaluate_ and _make train_ ?
To get the final results, how should i conduct the command from the Makefile in order?

**Comment by cs-mshah** [comment]
`make evaluate` is for evaluating the mAP of the initial pseudo labels depending on the config. To generate the initial pseudo labels, you need to run `make clip_cache` and `make clip_cache0`. Once this is generated, for training you can run `make train`. As of now setting `pseudo_update_frequency: 10` and `max_epochs: 100` has only given some decent results. Running for 20 epochs and warmup 3 doesn't seem to give any good results.

Let me know if this clears your doubt.

**Comment by harukaza** [comment]
Thanks for your respond. It helps for me!
